In [2]:
import pandas  as pd 
import numpy as np  
import matplotlib.pyplot as plt 


In [3]:
# Import training set 
path=r"C:\Users\ladom\Desktop\LLm\data\Google_Stock_Price_Train.csv"
df=pd.read_csv(path)
training_set=df.iloc[:, 1:2].values

In [4]:
from sklearn.preprocessing import MinMaxScaler 
# Feature Scaling
sc=MinMaxScaler(feature_range=(0,1)) 
training_set_scaled=sc.fit_transform(training_set)
training_set_scaled



array([[0.08581368],
       [0.09701243],
       [0.09433366],
       ...,
       [0.95725128],
       [0.93796041],
       [0.93688146]])

In [5]:
# Creating a data structure with 60 timestamps and 1 output 
X_train=[] 
y_train=[] 
for v in range(60 ,1258): 
    X_train.append(training_set_scaled[v-60:v, 0]) 
    y_train.append(training_set_scaled[v, 0])
X_train, y_train =np.array(X_train), np.array(y_train)
print(X_train)
print(f"y_train {y_train}")

    
    

[[0.08581368 0.09701243 0.09433366 ... 0.07846566 0.08034452 0.08497656]
 [0.09701243 0.09433366 0.09156187 ... 0.08034452 0.08497656 0.08627874]
 [0.09433366 0.09156187 0.07984225 ... 0.08497656 0.08627874 0.08471612]
 ...
 [0.92106928 0.92438053 0.93048218 ... 0.95475854 0.95204256 0.95163331]
 [0.92438053 0.93048218 0.9299055  ... 0.95204256 0.95163331 0.95725128]
 [0.93048218 0.9299055  0.93113327 ... 0.95163331 0.95725128 0.93796041]]
y_train [0.08627874 0.08471612 0.07454052 ... 0.95725128 0.93796041 0.93688146]


In [6]:
# Reshaping
X_train= np.reshape(X_train,(X_train.shape[0], X_train.shape[1],1))
X_train

array([[[0.08581368],
        [0.09701243],
        [0.09433366],
        ...,
        [0.07846566],
        [0.08034452],
        [0.08497656]],

       [[0.09701243],
        [0.09433366],
        [0.09156187],
        ...,
        [0.08034452],
        [0.08497656],
        [0.08627874]],

       [[0.09433366],
        [0.09156187],
        [0.07984225],
        ...,
        [0.08497656],
        [0.08627874],
        [0.08471612]],

       ...,

       [[0.92106928],
        [0.92438053],
        [0.93048218],
        ...,
        [0.95475854],
        [0.95204256],
        [0.95163331]],

       [[0.92438053],
        [0.93048218],
        [0.9299055 ],
        ...,
        [0.95204256],
        [0.95163331],
        [0.95725128]],

       [[0.93048218],
        [0.9299055 ],
        [0.93113327],
        ...,
        [0.95163331],
        [0.95725128],
        [0.93796041]]])

# Part 2 bulding the RNN 

In [7]:
from keras.models import Sequential 
from keras.layers import Dense 
from keras.layers import LSTM 
from keras.layers import Dropout 

# Initialising the RNN 
regressor=Sequential() 
# Add LSTM layers and some Dropout redularisation
regressor.add(LSTM(units=50, return_sequences=True, input_shape=(X_train.shape[1], 1))) 
regressor.add(Dropout(0.2))
regressor.add(LSTM(units=50, return_sequences=True)) 
regressor.add(Dropout(0.2))
regressor.add(LSTM(units=50, return_sequences=True)) 
regressor.add(Dropout(0.2))
regressor.add(LSTM(units=50)) 
regressor.add(Dropout(0.2))
regressor.add(Dense(units=1))

C:\Users\ladom\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [8]:
# Compile the RNN 
regressor.compile(optimizer="adam", loss="mean_squared_error")

In [9]:
# Optimizing epochs and Batch Size 
regressor.fit(X_train, y_train, epochs=100, batch_size=32)



Epoch 1/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 7s 58ms/step - loss: 0.0455
Epoch 2/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 51ms/step - loss: 0.0058
Epoch 3/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 51ms/step - loss: 0.0055
Epoch 4/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 65ms/step - loss: 0.0060
Epoch 5/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 68ms/step - loss: 0.0048
Epoch 6/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 62ms/step - loss: 0.0049
Epoch 7/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 61ms/step - loss: 0.0045
Epoch 8/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 62ms/step - loss: 0.0047
Epoch 9/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 62ms/step - loss: 0.0043
Epoch 10/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 62ms/step - loss: 0.0049
Epoch 11/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 61ms/step - loss: 0.0042
Epoch 12/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 60ms/step - loss: 0.0041
Epoch 13/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 63ms/step - loss: 0.0039
Epoch 14/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 62ms/step - loss: 0.0041
Epoch 15/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 65ms/step - lo

# Part 3 Making the prediction and visualising the result

In [11]:
test_path=r"C:\Users\ladom\Desktop\LLm\data\Google_Stock_Price_Test.csv"
dataset_test=pd.read_csv(test_path)
real_stock_price=dataset_test.iloc[:, 1:2].values

In [16]:
dataset_total=pd.concat((df['Open'], dataset_test['Open']), axis=0) 
inputs=dataset_total[len(dataset_total)-len(dataset_test)-60:].values
inputs=inputs.reshape(-1,1)
inputs=sc.transform(inputs)

In [21]:
# Visualising the result 
X_test=[] 
for i in range(60, 80):
    X_test.append(inputs[i-60:i, 0])
X_test=np.array(X_test)
X_test=np.reshape(X_test, (X_test.shape[0], X_test.shape[1],1))
predicted_stock_price=regressor.predict(X_test)
predicted_stock_price= sc.inverse_transform(predicted_stock_price)
predicted_stock_price

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step


array([[774.9746 ],
       [772.61597],
       [772.5886 ],
       [773.6111 ],
       [776.4111 ],
       [781.5555 ],
       [786.6057 ],
       [789.1498 ],
       [789.9616 ],
       [789.9819 ],
       [789.7478 ],
       [789.372  ],
       [789.03534],
       [789.32825],
       [790.0904 ],
       [793.9991 ],
       [800.1347 ],
       [807.0401 ],
       [811.33356],
       [808.6786 ]], dtype=float32)