In [26]:
import tensorflow as tf 
import pandas as pd 
import numpy as np 


In [57]:
path=r"C:\Users\ladom\Desktop\LLm\data\Churn_Modelling.csv"
df=pd.read_csv(path)

# Drop unnecessary columns
df_processed = df.drop(['RowNumber', 'CustomerId', 'Surname', 'Exited'], axis=1)
y = df['Exited'].values

# Keep track of numerical and categorical columns
cat_cols = ['Geography', 'Gender']
num_cols = [col for col in df_processed.columns if col not in cat_cols]

print("Numerical columns:", num_cols)
print("Categorical columns:", cat_cols)

Numerical columns: ['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary']
Categorical columns: ['Geography', 'Gender']


Label encoding

One Hot encoding "Geography" column

In [ ]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer

# Create preprocessing steps for both categorical and numerical columns
preprocessor = ColumnTransformer(
    transformers=[
        ('num', 'passthrough', num_cols),
        ('cat', OneHotEncoder(drop='first', sparse_output=False), cat_cols)
    ])

# Apply transformations
X = preprocessor.fit_transform(df_processed)
print("Shape after preprocessing:", X.shape)

Shape after encoding: (10000, 28)


In [55]:
# Splitting dataset into Training and Test set 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y, test_size=0.2, random_state=0)
print(X)

[[1.0 0.0 1.0 ... 1 1 101348.88]
 [0.0 1.0 0.0 ... 0 1 112542.58]
 [1.0 0.0 1.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 1.0 ... 0 1 42085.58]
 [1.0 0.0 1.0 ... 1 0 92888.52]
 [1.0 0.0 1.0 ... 1 0 38190.78]]


In [56]:
# Feature Scaling 
from sklearn.preprocessing import StandardScaler 
sc=StandardScaler() 
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

ValueError: could not convert string to float: 'Spain'